# -*- coding: utf-8 -*-
"""decitree_iris.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14EfI4VQiML-NuQLrv1oxPDGLtQa6OELQ
"""

from sklearn.datasets import load_iris
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# now loading IRIS data only
iris=load_iris()

dir(iris)  # exploring variable

iris.DESCR    # description of iris

iris.feature_names   # these are features names

#label answer
iris.target_names

#actual data with attributes is
features = iris.data
# features   shows iris data
features.shape

#now time for label data that will be exactly same as no. of fatures data
label=iris.target
label.shape

SL=features[0:,0]

SW=features[0:,1]

plt.xlabel("Sepal Length")
plt.ylabel("Sepal Width")
plt.scatter(SL,SW,label="sepal data",marker="*")
plt.scatter(features[0:,2],features[0:,3],label="petal_data",marker="x")
plt.legend()

# now time for separating data into two category 
# 1....training data
# 2....testing data.....Questions
from sklearn.model_selection import train_test_split
train_data,test_data,label_train,label_test=train_test_split(features,label,test_size=0.1)
3

# calling decision tree classifier
clf=DecisionTreeClassifier()

# now time for training clf
trained = clf.fit(train_data,label_train)

# now predicting flower
predicted_flowers=trained.predict(test_data)
predicted_flowers  # algo answer

label_test     # actual answer

# find accuracy score
accuracy_score(label_test,predicted_flowers)

